### ISSUE TITLE
[Question] try_map usage of `s`

### ISSUE THREAD

**Issue by TornaxO7** [zesterer/chumsky#163]
Hello, I've got a little question to [this line](https://github.com/zesterer/chumsky/blob/master/src/lib.rs#L392): What is `s`? Could you please add a little description about this variable or give the variable a more understandable name?

**Comment by zesterer** [comment]
The output type of `text::int` [is a `String`](https://docs.rs/chumsky/latest/chumsky/text/fn.int.html). `s` in `try_map` is this string, and we're parsing it using Rust's [standard string parsing function](https://doc.rust-lang.org/std/primitive.str.html#method.parse) in the closure. Because parsing it fallible, `try_map` is used to allow the error case to be handled by chumsky.

Does this help?

**Comment by TornaxO7** [comment]
Oh, yes it does, thank you!
