### ISSUE TITLE
Add a `many_till` combinator

### ISSUE THREAD

**Issue by lightningyx** [zesterer/chumsky#176]
I propose a combinator that repeats the first parser until the second one matches.

[nom](https://github.com/Geal/nom) has an equivalent combinator:
https://docs.rs/nom/7.1.1/nom/multi/fn.many_till.html

The output type would be `(Vec<A>, B)`,
`A` and `B` being the output types of the given parsers.

**Comment by Zij-IT** [comment]
I may be misunderstanding you, but wouldn't such a combinator be the equivalent of:

    just(A).repeated().then(just(B))

You can see this being used in Zesterer's [foo implementation](https://github.com/zesterer/chumsky/blob/master/examples/foo.rs#L54-L57).

**Comment by lightningyx** [comment]
> I may be misunderstanding you, but wouldn't such a combinator be the equivalent of:
> 
> ```
> just(A).repeated().then(just(B))
> ```

I should've explained more clearly.

The docs for `nom::multi::many_till` say:
> Applies the parser `f` until the parser `g` produces a result.

I guess the description for the parser you suggested would be:
Applies the Parser `f` any number of times,
then applies the parser `g`.

So while the `many_till` parser applies `f` lazily, your one applies it eagerly.
I think you can use these two parsers interchangeably,
until you have a case where `f` and `g` could parse the same input.
Then the `many_till` parser would parse `g`, and your one would parse `f`.

If I'm not mistaken, it looks like the examples in the nom docs and for the foo implementation
are just such cases where you could use your parser as well.

**Comment by vmarkushin** [comment]
I would like to have a similar combinator (I would call it `repeated_until` instead) because I don't see a way to express such logic with the existing combinators.

Example (abstract code): 
```rust
let x = "d"
let input = "a b c d"
let parser = any().repeated_until(x)
parser.parse(input) == ["a", "b", "c"]
```

**Comment by zesterer** [comment]
So really, you want something like

`a.and_is(b.not()).repeated().then(b)`?

i.e: lazily consume `a`, provided it *doesn't* match `b`, and then consume a `b`?

**Comment by lightningyx** [comment]
Yes, exactly 🙂

**Comment by zesterer** [comment]
Right. In that case, I'll probably close this in favour of #181 because it contains a little more discussion about these.

**Comment by Hedgehogo** [comment]
> So really, you want something like
> 
> `a.and_is(b.not()).repeated().then(b)`?
> 
> i.e: lazily consume `a`, provided it _doesn't_ match `b`, and then consume a `b`?

This works, however what if the `b` parser is expensive? This kind of code requires calling it an extra time, repeating calculations already performed. For example it could be a parser that absorbs a single Unicode grapheme cluster (from some subset), in most cases this is a cheap operation but could potentially take any amount of time. Also, in an extremely rare case it may call impure code and then the proposed replacement is logically different at all.

**Comment by Zij-IT** [comment]
> Also, in an extremely rare case it may call impure code and then the proposed replacement is logically different at all.

I don't believe `chumsky` makes guarantees for what is to happen with an impure code, as it is free to optimize away `map` if it knows that the input is going to be dropped, such as with the `Ignore` parser.

**Comment by zesterer** [comment]
Yep, no guarantees are made. The closure of a `.map` might be invoked any number of times and should be logically pure.

> This works, however what if the b parser is expensive?

I'm definitely sympathetic to this argument. We had `take_until` in chumsky 0.9, but I made the decision to remove it because there was a lot of debate about exactly what it should do:

- Should it consume the terminating pattern?
- Should it include the terminating pattern in the output?
- What happens if the input is ambiguous between the terminating pattern and the repeating pattern?

There are several possible designs, all of which have competing constraints, none of which felt objectively superior to the others. I ended up getting rid of it for 1.0 in favour of `and_is` and `not` because, together, those combinators are far more general.

Out of interest, do you have a case that demonstrably does not optimise as well as it should?

**Comment by Hedgehogo** [comment]
Further in the text, `a` is the repeating parser and `b` is the terminating parser.

> Should it consume the terminating pattern?

Yes, in cases where it is needed it is useful, in cases where it is not needed you can use `a.repeated_till(b.rewind())` or `b.not().then(a).repeated()`. The alternative is less convenient, since it will require `b` to be re-parsed when consummation is still required.

> Should it include the terminating pattern in the output?

Yes, if you don't need the result you can get rid of it with `map`. You can also remove the unnecessary result by adding a separate version of the parser that does not return it or by adding a parser that ignores the second tuple element in the result of any parser. The alternative version does not return the result at all, which makes it narrower in its application.

> What happens if the input is ambiguous between the terminating pattern and the repeating pattern?

The final pattern is prioritized, since the original point of a parser like this is to make a lazy repeated parser. For a greedy parser there is already `a.repeated().then(b)`.

Also `repeated_till` must have another property that is not repeated by any of the proposed replacements. If both `a` and `b` return an error, then these errors must be merged, not just the error from `b`.

> Out of interest, do you have a case that demonstrably does not optimise as well as it should?

I don't have such an example.
