### ISSUE TITLE
Repeated choice containing repeated panics

### ISSUE THREAD

**Issue by msrd0** [zesterer/chumsky#186]
The following code panics when executed:

```rust
#[test]
fn repeated_is_broken() {
	fn parser() -> impl Parser<char, Vec<String>, Error = Simple<char>> {
		choice((
			just("{{").map(|_| String::new()),
			none_of("{").repeated().map(|vec| vec.into_iter().collect())
		))
		.repeated()
		.then_ignore(end())
	}

	let token = parser().parse("foo").unwrap(); // panic happens here
	assert_eq!(&token, &["foo"]);

	let token = parser().parse("{{").unwrap();
	assert_eq!(&token, &[""]);
}
```

```
thread 'repeated_is_broken' panicked at 'Repeated parser iteration succeeded but consumed no inputs (i.e: continuing iteration would likely lead to an infinite loop, if the parser is pure). This is likely indicative of a parser bug. Consider using a more specific error recovery strategy.', /home/msrd0/.cargo/git/checkouts/chumsky-651fb76526ac39e3/b4b0229/src/combinator.rs:484:25
```

Removing either call to `repeated` removes the panic (but also changes what the parser does).

Happens both with the latest release and current git version.

**Comment by zesterer** [comment]
Your parser contains two a pattern that accepts no input (`none_of("{").repeated()`) inside a `.repeated()`, leading to an infinite loop. The panic is warning you about this, because it's almost always a bug when it happens. You should force the inner `.repeated()` or parse at least some input with `.at_least(1)` or similar.

**Comment by msrd0** [comment]
Thanks, using `at_least(1)` works
