### ISSUE TITLE
Example of Python-like parsing

### ISSUE THREAD

**Issue by VinnyVicious** [zesterer/chumsky#20]
Having an example on how to parse Python-like languages that are aware of indentation would be interesting.

**Comment by zesterer** [comment]
Python's parser/lexer (whichever processes identations) is not context-free because correctly parsing each line relies on the contextual information available in previous lines (i.e: lines 'pair up' with neighbouring lines into blocks if their indentation matches).

Chumsky (and virtually all parser combinators and parser generators) do not play well with context-sensitive grammars. It's usually necessary to hand-write a context-sensitive parser for such languages.

All is not lost, however! A neat trick you can use is to write your lexer by hand and have it translate Pythonic indentation into traditional code blocks with delimiters. Once this is done, the tokens can be fed into Chumsky and parsed in a context-free manner.

I would actually advise you use this strategy: get rid of the context-sensitive indentation as early as you possibly can in the compiler, it makes parsing in general needlessly complex.

I've actually written an example lexer that does this in the past, complete with correct handling of parentheses and newlines. You can take a look at it [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=39f089d64a36f8535c4696170e8b6e0e). Once you've turned the text into a stream of tokens, they're pretty easy to feed to Chumsky.

It's probably possible to implement something similar as custom parser for Chumsky too, although it's obviously a bit ugly for the reasons I mentioned above. I'll look into this a little more to see if it's possible.

**Comment by VinnyVicious** [comment]
Thank you for the detailed answer and the bonus example! Really appreciate it.

**Comment by Xandaros** [comment]
Something I have seen before is introducing special `INDENT` and `OUTDENT` tokens in your lexer. I thought that was quite clever.

**Comment by LikeLakers2** [comment]
@zesterer Apologies for the bump after two weeks, but I'm curious.

> I'll look into this a little more to see if it's possible.

If it turns out not to be possible, could an indent-aware parsing example still be included in the `/examples/` directory? That way, users would know how they might make Chumsky work with indent-aware content, even if it requires some hand-written code on their end.

**Comment by zesterer** [comment]
I've had a think about it and although I believe that it should be possible to implement, I don't think that any implementation I could add to Chumsky would be sufficiently flexible to cover all use-cases.

In terms of a hand-written example implementation, I'm very happy to accept something like this if someone is interested in implementing it. Right now, unfortunately, I'm focusing on a number of other things so I likely won't get time to work on it until after New Year.

**Comment by zesterer** [comment]
I've actually made some progress on this! `master` now contains a parser called `semantic_whitespace` that can be used to tokenise Python-style syntax into token trees, respecting semantic indentation. You can find an example of its use [here](https://github.com/zesterer/chumsky/blob/master/examples/pythonic.rs).

I'd really like feedback about how this function might be improved: I'm sure that it's not general enough for some cases, but it's not yet clear to me how best to generalise it. Thoughts would be very welcome!

**Comment by tatsuya6502** [comment]
Hi @zesterer,

Thank you for adding the `semantic_whitespace` parser. It looks promising!

I am new to Chumsky so it took me a while to figure out how to feed the nested token trees from the lexing stage to the next stage. I think I need to use `Stream::from_nested` to create a flattened token stream before feeding them to the parser.

I am hoping the exsample could demonstrate that too. So I have updated the example [here](https://github.com/tatsuya6502/chumsky/blob/4a8ebb07055e89a2a59cbf0c05c8279aea6e6981/examples/pythonic.rs#L115). Am I on the right track? or is there any better way?

**Comment by VinnyVicious** [comment]
Could that approach be merged back to master?

**Comment by zesterer** [comment]
> Hi @zesterer,
> 
> Thank you for adding the `semantic_whitespace` parser. It looks promising!
> 
> I am new to Chumsky so it took me a while to figure out how to feed the nested token trees from the lexing stage to the next stage. I think I need to use `Stream::from_nested` to create a flattened token stream before feeding them to the parser.
> 
> I am hoping the exsample could demonstrate that too. So I have updated the example [here](https://github.com/tatsuya6502/chumsky/blob/2c1312f8baeac66fecea1f5f75d0036aa721f0c5/examples/pythonic.rs#L115). Am I on the right track? or is there any better way?

Hey, sorry it took so long to respond to this!

Yes, this approach works fine for now. That said, I'm a little hesitant to recommend it as a long-term solution because it's quite verbose. I'm still hopeful that there's a way to add support for parsing token trees into the `zero-copy` branch, but it seems... *mechanically complicated* to say the least.

Could you open a PR with this change? I think it's merge-worth still, provided it's made clear that the `Stream::from_nested` is conceptually distinct from the lexing stage.

**Comment by ehllie** [comment]
I'm not certain if the example is meant to cover this, but the pythonic parser does not enforce that the individual tokens be separated by whitespace, meaning ambiguous syntax like
```py
10foo:
    20bar
```
Gets parsed to: `[(Int(10), 0..2), (Ident("foo"), 2..5), (Op(":"), 5..6), (Open(Block), 9..14), (Int(20), 9..11), (Ident("bar"), 11..14), (Close(Block), 9..14)]`
I could not figure out how to enforce that while using the `semantic_whitespace` parser, but that could be down to me not understanding the library well enough yet.

**Comment by zesterer** [comment]
The `pythonic` example is just a very simple example, not a full parser for Python code. The issue you're seeing is unrelated to `semantic_whitespace`, it's just a product of it being a simple example rather than a fully-fledged parser.

**Comment by zesterer** [comment]
@TTTPOB 

It's quite likely that `semantic_indentation` has either a bug or is not quite able to express what you want: it's a stop-gap for chumsky's (current) lack of true context-sensitive parsing, which is required to parse Python-style indentation properly.

However, there's rapid movement on this front! The `zero-copy` branch (due for merge soon) is getting a rugged, powerful system for expressive context-sensitive parsing. You can see an example of this being used to parse Python-style indentation [here](https://github.com/zesterer/chumsky/pull/269#issuecomment-1422968962).

If you feel you can't wait for `zero-copy` and a new release (I suspect it's probably about a month away), my best advice would be to parse indentation in a hand-written lexer and pass it on to chumsky as delimiter token, such as C-style braces.

**Comment by TTTPOB** [comment]
> If you feel you can't wait for zero-copy and a new release (I suspect it's probably about a month away), my best advice would be to parse indentation in a hand-written lexer and pass it on to chumsky as delimiter token, such as C-style braces.

Thank you! it looks promising, I will try to write a lexer first, and maybe switch to the new release after.

**Comment by zesterer** [comment]
`zero-copy` now supports context-sensitive parsing (see #269), enough to properly implement Python style indentation sensitivity (and much more!).

**Comment by VinnyVicious** [comment]
@zesterer this is fantastic. Thank you so much for all the hard work on this.
