### ISSUE TITLE
Parser works by itself but doesn't consume any input with .repeated() applied

### ISSUE THREAD

**Issue by thatbakamono** [zesterer/chumsky#205]
```rs
fn node_parser() -> impl Parser<char, Node, Error = Simple<char>> {
    let text = filter(|character: &char| {
        !character.is_ascii_control() && *character != '<' && *character != '>' && *character != '&'
    }).repeated().collect::<String>();

    let text = text.padded().map(Node::Text);

    text
}

fn document_parser() -> impl Parser<char, Document, Error = Simple<char>> {
    node_parser()
        .map(|node| Document { nodes: vec![node] })
        .then_ignore(end().recover_with(skip_then_retry_until([])))
}
```
```rs
fn node_parser() -> impl Parser<char, Node, Error = Simple<char>> {
    let text = filter(|character: &char| {
        !character.is_ascii_control() && *character != '<' && *character != '>' && *character != '&'
    }).repeated().collect::<String>();

    let text = text.padded().map(Node::Text);

    text
}

fn document_parser() -> impl Parser<char, Document, Error = Simple<char>> {
    node_parser()
        .repeated()
        .map(|nodes| Document { nodes })
        .then_ignore(end().recover_with(skip_then_retry_until([])))
}
```

The former works without any issues (it obviously consumes input), while the latter doesn't and errors out saying `Repeated parser iteration succeeded but consumed no inputs (i.e: continuing iteration would likely lead to an infinite loop, if the parser is pure). This is likely indicative of a parser bug. Consider using a more specific error recovery strategy.`

I used this simple unit test to test everything
```rs
#[test]
fn parse_text() {
    assert_eq!(Document::parse("Lorem ipsum dolor sit amet"), Document {
        nodes: vec![
            Node::Text(String::from("Lorem ipsum dolor sit amet")),
        ],
    });
}
```

`Document::parse` doesn't really do anything important or related to the issue but I will include it either way for completeness
```rs
impl Document {
    pub fn parse(input: &str) -> Self {
        document_parser()
            .parse(input)
            .expect("Failed to parse the specified input.")
    }
}
```

**Comment by mattfbacon** [comment]
`node_parser` is able to not consume input, though. You never added a lower bound on the `repeated` call. Maybe you should put `.at_least(1)` or similar.

**Comment by thatbakamono** [comment]
I use `repeated` in a lot of different places, not only this one and a lower bound doesn't seem to be required, also, I would want the parser to be able to also parse no input at all, so `at_least(1)` won't do the trick.

**Comment by zesterer** [comment]
The problem here is that `node_parser` can consume no inputs (it's got a `.repeated()` at the top level, and `repeated` is permitted to accept nothing. Then, just below in `document_parser`, you're adding another `.repeated()` on the end of it.

i.e: you effectively have `foo.repeated().repeated()`.

If the parser hits an input it can't match (an ASCII control character, `<`, `>`, `&`, or even just the end of input), `foo.repeated()` will *always* succeed because it can just bail and produce an empty vector (i.e: none of `foo` were parsed).

The problem comes with the second `.repeated()`: now, you're telling the parser to parse *a potentially infinite number of things at consume no input*. Obviously, this is akin to telling the parser to enter into an infinite loop, and the panic message is telling you this.

@mattfbacon is correct: the first `.repeated()` should have a `.at_least(1)` on the end of it. forcing the `node_parser` to consume at least one character before proceeding.

**Comment by thatbakamono** [comment]
Oh, I misunderstood him, I thought he was talking about the second `.repeated()`. I added `.at_least(1)` after the first `.repeated()` and it solved the issue, thanks.
