### ISSUE TITLE
[0.9.0] `Parser::chain()` becomes too generic to require additional type annotations at many places

### ISSUE THREAD

**Issue by rnarkk** [zesterer/chumsky#272]
This implementation (https://github.com/zesterer/chumsky/releases/tag/0.9)

> `Option<Vec<T>>` and `Vec<Option<T>>` now implement `Chain<T>` ..

causes an abundance of possible type candidates, requiring us to give additional type parameter information at many places:

> error[E0283]: type annotations needed
   --> src/FILE.rs:N:M
    |
N |    CODE
    |      ^^^^^ cannot infer type of the type parameter `U` declared on the associated function `chain`
    |
    = note: multiple `impl`s satisfying `Vec<_>: chumsky::chain::Chain<_>` found in the `chumsky` crate:
            - impl<T> chumsky::chain::Chain<T> for T;
            - impl<T> chumsky::chain::Chain<T> for Vec<Option<T>>;
            - impl<T> chumsky::chain::Chain<T> for Vec<T>;
note: required by a bound in `chumsky::Parser::chain`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/chumsky-0.9.0/src/lib.rs:704:12

Can we implement different methods (such as `chain_iter`/`chain_many`, `chain_option`/`chain_unwrap`) having different signatures, instead of giving one trait to different (but equally quantification-related) types?

**Comment by zesterer** [comment]
This is indeed unfortunate and undesirable.

Resolving this *should* be relatively easy in practice: [As you can see](https://docs.rs/chumsky/latest/chumsky/trait.Parser.html#method.chain), the second type parameter is the one to collect into, so `.chain::<_, Vec<Option<_>>, _>()` (for example) should be sufficient for the compiler to disambiguate between the impls.

I am somewhat reluctant to put substantial work into resolving this, however, because `chain` has been ripped out in the [`zero-copy` rewrite](https://github.com/zesterer/chumsky/pull/82), given that `map_slice` covers almost all use-cases much more efficiently and elegantly and with fewer ugly corner cases (such as this very issue, for example).

I hope this answer isn't too disappointing.
