### ISSUE TITLE
Regression: `choice` in combination with `skip_then_retry_until` causes infinite loop

### ISSUE THREAD

**Issue by remkop22** [zesterer/chumsky#301]
The example below produces an infinite loop.

If I replace the `choice` with a chain of `or` calls this does not occur.

This only happens in version `0.0.9`.

```rust
#[derive(Debug, Clone, Copy)]
pub enum Token {
    Foo,
    Bar,
}

fn lexer() -> impl Parser<char, Token, Error = Simple<char>> {
    let foo = just("foo").to(Token::Foo);
    let bar = just("bar").to(Token::Bar);

    choice((foo, bar)).recover_with(skip_then_retry_until([]))
}

fn main() {
    println!("{:?}", lexer().parse("baz").expect("invalid input"));
}
```

**Comment by jim-ec** [comment]
I can take a look at the bug this week.

As for the changes, I explained them in the PR #148.

**Comment by zesterer** [comment]
I think the revert was premature in hindsight. I'm going to look into this specific case a little more, so don't worry.

**Comment by zesterer** [comment]
Right, now I've *actually* fixed this. Turns out that the issue was that the stream state wasn't being reverted when the parse attempt failed, and the change you made @jim-ec seemed to just hide that problem by not committing to consuming a token. Had me stumped for quite a while, I've added @remkop22's original code as a test to catch this.

**Comment by jim-ec** [comment]
Great, and also thanks for letting me know. Thanks for your great parser library @zesterer!
