### ISSUE TITLE
Syntax serialization (railroad diagrams)

### ISSUE THREAD

**Issue by Twixes** [zesterer/chumsky#32]
Hey! I'm rolling an SQL parser, and I want to generate railroad diagrams of the syntax ([SQLite style](https://www.sqlite.org/lang_createtable.html#syntax)) – I think they are beautifully helpful – probably with https://github.com/lukaslueg/railroad. What's the simplest way of going about this with Chumsky automatically (if there is one)?

**Comment by zesterer** [comment]
I think you'd probably want to use Chumsky 'as normal' to generate and AST, and then use Railroad on the final AST. I have examples that show you how to generate ASTs in this repository and in the doc examples. Although Chumsky may eventually gain some form of graphic debugging output, it'll be tailored more towards introspecting the parser rather than the semantics of the input itself.

There exist [decent Rust SQL parsers already](https://lib.rs/crates/sqlparser) so, provided their error handling is good enough for you, it would probably be easier to plug the AST generated by one of them into Railroad directly.

**Comment by Twixes** [comment]
What do you mean by 'as normal'?

Re: `sqlparser`, I do think it's great, though I want to diverge from the SQL standard in a few places and also I just think building parsers is fun ;) so currently I have my own purely functional parser which I was thinking of replacing with Chumsky. Having access to the structure of the syntax would be a plus – since easier to have in an approach based on `impl Parser` structs than in function composition.

**Comment by zesterer** [comment]
> What do you mean by 'as normal'?

Parsing SQL into an AST with Chumsky, I mean.

> I want to diverge from the SQL standard 

Fair enough. In that case, Chumsky is probably a good choice.

> Having access to the structure of the syntax would be a plus

Chumsky gives you the ability to map your syntax to an AST. There are examples of this in the repository.
