### ISSUE TITLE
1.0.0-alpha.0: `then_ignore`/`ignore_then` don't ignore

### ISSUE THREAD

**Issue by CobaltCause** [zesterer/chumsky#325]
```diff
diff --git a/examples/zero-copy.rs b/examples/zero-copy.rs
index 4c37caa..ec03e36 100644
--- a/examples/zero-copy.rs
+++ b/examples/zero-copy.rs
@@ -15,8 +15,8 @@ fn parser<'a>() -> impl Parser<'a, &'a str, [(SimpleSpan<usize>, Token<'a>); 6]>
         .map_slice(Token::Ident);

     let string = just('"')
-        .then(any().filter(|c: &char| *c != '"').repeated())
-        .then(just('"'))
+        .ignore_then(any().filter(|c: &char| *c != '"').repeated())
+        .then_ignore(just('"'))
         .map_slice(Token::String);

     ident
```

If you apply this patch on top of 29e0fb545801b62430568c2f161160fd5d71ff4c and run the example, the assert still passes because the `"`s in the `Token::String`s aren't filtered out like they should be. (Maybe I'm just missing something?)

**Comment by CobaltCause** [comment]
> (Maybe I'm just missing something?)

Yep I'm actually just dumb, this causes the assert to fail in the way that I want:

```diff
diff --git a/examples/zero-copy.rs b/examples/zero-copy.rs
index 4c37caa..275aa01 100644
--- a/examples/zero-copy.rs
+++ b/examples/zero-copy.rs
@@ -15,9 +15,9 @@ fn parser<'a>() -> impl Parser<'a, &'a str, [(SimpleSpan<usize>, Token<'a>); 6]>
         .map_slice(Token::Ident);

     let string = just('"')
-        .then(any().filter(|c: &char| *c != '"').repeated())
-        .then(just('"'))
-        .map_slice(Token::String);
+        .ignore_then(any().filter(|c: &char| *c != '"').repeated().slice())
+        .then_ignore(just('"'))
+        .map(Token::String);

     ident
         .or(string)
```

Thanks for the great library! :sweat_smile:

**Comment by bew** [comment]
Yeah, this is because `map_slice` doesn't take ignores into account.
Related: #243

**Comment by zesterer** [comment]
Just to make clear for anybody else reading this in the future, there's a subtle conflation going on here that I should probably clarify more in the docs:

- `then_ignore` simply drops the output of the latter parser (or, at least, observably has that behaviour). The latter parser still consumes input, as any other parser does

- `map_slice` gets its slice purely from the input position at which the parser started parsing, and the input position at which it finished. It does not 'know' about ignores, nor are ignores something that get signalled to other parsers. In fact, because `map_slice` drops the output of the previous parser in favour of the slice, `a.then_ignore(b).map_slice(...)` actually has the same observable behaviour as `a.then(b).map_slice(...)`

**Comment by zesterer** [comment]
Whoops, mis-tap

**Comment by ctron** [comment]
I just ran into the same issue and come up with the following:

```rust
let s = just('"')
    .ignore_then(none_of('"').repeated().slice())
    .then_ignore(just('"'));
```

**Comment by zesterer** [comment]
> I just ran into the same issue and come up with the following:

Just FYI, this is equivalent to:

```rs
let s = none_of('"').repeated().slice()
    .delimited_by(just('"'), just('"'));
```

I personally find `delimited_by` to be a fair bit easier to read.
