### ISSUE TITLE
Nested and Clone

### ISSUE THREAD

**Issue by stefnotch** [zesterer/chumsky#328]
https://github.com/zesterer/chumsky/blob/main/examples/nested.rs has an example of how to parse a nested datastructure. One tidbit that worries me is that the `Token` has to implement `Clone`. Could that become very expensive when someone has a large token tree?

If yes, what's the suggested solution?

**Comment by zesterer** [comment]
You make a good point, I should rework some of the combinators so that they use a distinct `CloneInput` trait (sort of like `BorrowInput`.

**Comment by stefnotch** [comment]
Glad to hear that I didn't just overlook something obvious. Then I'll look forward to your future changes to this lovely library :)

**Comment by zesterer** [comment]
So I've been prototyping ways to remove the `Clone` bound.

It turns out to be much harder than I thought because token cloning is used often for generating errors. It's probably going to require some somewhat more aggressively changes to the public API, unfortunately, and will almost certainly require changes to the way we represent errors.

I've a prototype working in #329 (in particular, note that [the `nested.rs` example](https://github.com/zesterer/chumsky/blob/cec0cb8b0cdb95d26f19632665b88920b3965d4e/examples/nested.rs) works with the `Clone` bound removed from `Token`).

**Comment by zesterer** [comment]
After discussion with CraftSpider, we've come to the conclusion that despite the minor downsides, #329 is a substantial enough advantage over the current status of things to be merged.

Thanks for pointing out this issue with the API, all should be resolved now!

**Comment by stefnotch** [comment]
Oh my gosh, that's the fastest response time to a quite substantial library decision that I have ever gotten. 

Thank you very much for pulling that off, I really appreciate it!

**Comment by zesterer** [comment]
It does help that we're still in the alpha phase so we don't care so much about breaking changes! :grinning:
