### ISSUE TITLE
`example/nano_rust.rs` has a broken error reporting on duplicated fn names

### ISSUE THREAD

**Issue by LunaAmora** [zesterer/chumsky#382]
I was trying to follow the nano_rust example on the latest alpha (1.0.0-alpha.3) and couldn't understand why i couldn't implement the duplicated fns error correctly. After some experimentation, i found that the error was already like that when i cloned the repo and executed the example file with any extra duplicated fn.

![image](https://user-images.githubusercontent.com/19491161/226118940-290e839f-5bab-47a7-887f-8db5b75419ed.png)

**Comment by zesterer** [comment]
This looks to the confluence of two issues:

1) There's a 'bug' in the `nano_rust` parser that doesn't permit it to accept empty blocks, so `{}` is considered invalid.

2) `try_map` (which actually abandons parsing when an error occurs) is used for checking duplicate function definitions despite duplicate errors being perfectly recoverable. I've switched the example to use `validate` [in this PR](https://github.com/zesterer/chumsky/pull/384/files).

With the latter change to `validate`, the error becomes:

![image](https://user-images.githubusercontent.com/3268430/226175592-56c20ec8-6630-4950-9882-7a9bf3732b13.png)

So still incorrect due to the aforementioned parser bug (which I will fix at some point), but much more understandable.

**Comment by LunaAmora** [comment]
On the first issue, my implementation supported empty blocks but still gave the `multiple errors` despite it being only one. So i kinda forgot to use a better example there :p

Thanks for the explanation, glad it's already on your radar!
