### ISSUE TITLE
Example with Ropes

### ISSUE THREAD

**Issue by edko99** [zesterer/chumsky#389]
Would it please be possible to include an example of how you would implement the `Input` trait for ropes (preferably ropey)?

**Comment by zesterer** [comment]
Knowing what I know about ropes, it sounds like only `Input` and `ValueInput` can be implemented for a rope: `SliceInput` is likely out of the question since the rope does not reveal contiguous slices of inputs. `BorrowInput` *may* be feasible, depending on the API that `ropey` provides.

You might find the existing implementations for [slice](https://github.com/zesterer/chumsky/blob/main/src/input.rs#L233-L305) useful if you're planning to fork and implement this upstream. Otherwise, I'd recommend using `Stream`.
