### ISSUE TITLE
recovery getting stuck on end()

### ISSUE THREAD

**Issue by Kingalidj** [zesterer/chumsky#459]
I wanted to parse the following code.

```rust
const SRC: &str = r"
def meter

- meter * s


second
joules

";
```
I first used logos to lex the different tokens and then built the parser with chumsky.
I wanted the parser to recover from an error by just replacing it with an error node and skip to the next line.

But no matter what i do i get this error: 'found Collect combinator making no progress at ...'
When i remove the two .recover_with(...) calles the parser works fine

Token::NL is a '\n'
```rust
        let body = just(Token::NL).repeated().ignore_then(

            expr.then_ignore(just(Token::NL).repeated().at_least(1).or(end()))

            .recover_with(via_parser(
                    end().map(|_| {
                        println!("end!");
                        Node::Err
                    })
                ))
            .recover_with(via_parser(
                    none_of(Token::NL).repeated().map(|x| {
                        println!("recover: {:?}", x);
                        Node::Err
                    })
                ))
        )
        .map(|x| {println!("parsed: {:?}", x); x})
        .repeated()
        .collect::<Vec<_>>().map(Node::Body)

```

this is the output:

```
parsed: Def("meter")
parsed: Mul(UnrySub(Unit("meter")), Unit("s"))
parsed: Unit("second")
parsed: Unit("joules")
end!
parsed: Err
thread 'main' panicked at 'found Collect combinator making no progress at ...'

```

**version**
1.0.0-alpha.4

**Comment by Zij-IT** [comment]
Can you please provide the rest of the code so that it can be tested locally? The issue is that your parser would never stop parsing, and `Collect` out this issue.

Let's walk through this as if we were your parser:

We have parsed all of the information and are sitting at the end of the input. Now we attempt to parse again. We can't parse an `expr`, so we attempt to recover with 

```rust
    end().map(|_| {
        println!("end!");
        Node::Err
    })
```

And we successfully recover, and output a `Node::Err`. So, we attempt to parse again, even though we haven't move further along the input. So we try again to parse `expr` and fail, and recover with the above recovery parser, and then output `Node::Err`... and again... and again.

The issue is that your recovery strategies are allowed to consume no input, and therefore will say that by collecting nothing they have successfully recovered. Without knowing more context of what you are hoping the parser does, and without being able to test it locally I can't provide a suggestion on how to get the behavior you desire.

So, to you:
* What would you like the parser to do?
* Can you provide more context so that the code can be reproduced locally?

**Comment by Kingalidj** [comment]
I found my mistake:
I thought that repeat() would always just automaticaly stop when reaching the end. after adding .at_least(1) after none_one(Token::NL)
it works.

Thanks!
