### ISSUE TITLE
RichReason Many

### ISSUE THREAD

**Issue by faassen** [zesterer/chumsky#474]
I'm using 1.0.0a4, and I'm returning a `Rich::custom` error from a `try_map`. I was surprised to find an error message like this:

```
multiple errors found at 7..8
```

That's not very informative at all. Plus the range is off - the custom error is actually returned for the token just *before* the "multiple errors" message.

Digging into it I found that this is happens because apparently multiple errors are combined into one using `RichReason::Many`: first my custom error happens, and then because that causes a token not to be parsed (I think?), the parser adds an `ExpectedFound` error. That's not what I intended; I just wanted to see the custom error for the correct span.

I'm not sure how to proceed. I see a TODO comment in the source code:

```
   // TODO: Should we really do this? Possibly better to just unify the unrelated reasons. It's not like consumers
    // probably care about reporting 5 different errors for the same location anyway!
```

Perhaps an improvement would be to show the custom error if `Many` contains any `custom`, because that's likely the intention of the user.

But I'm also puzzled why `try_map` continues parsing even though I've returned an error, as the docs say this:

```
After a successful parse, apply a fallible function to the output. If the function produces an error, treat it as a parsing error.

If you wish parsing of this pattern to continue when an error is generated instead of halting, consider using [Parser::validate](https://docs.rs/chumsky/1.0.0-alpha.4/chumsky/trait.Parser.html#method.validate) instead.
```

But parsing *is* apparently continuing when my custom error was generated, so I don't understand the behavior. Perhaps the docs are just obscure and the intention for `try_map` *is* to continue parsing other rules if it fails. If so, that warrants a documentation improvement.

**Comment by zesterer** [comment]
Hi,

This is probably something that needs changing as per the `TODO`. I think the original change was a little misguided and `Rich` should probably just choose one of the errors over another.

> But I'm also puzzled why try_map continues parsing even though I've returned an error

I'm not quite sure what is meant by this. You can think of `try_map` as being a bit like `Result::and_then`: if parsing is successful, the closure gets run and the success of the overall parser depends on the closure's return value.

**Comment by faassen** [comment]
Yeah, that's what I thought, it's just the text confused me, but I think I get it now:

```
If you wish parsing of this pattern to continue when an error is generated instead of halting, 
```

What *halting* refers to is not the entire parse but just the parse of this particular pattern. Perhaps a bit of verbiage surrounding what happens if an error occurs would help:

```
If the function produces an error, treat it as parsing error and parsing of this pattern halts. The rule does not match and Chumsky tries to match with another one. 

If you wish parsing of this pattern to continue when an error is generated instead of halting, consider using validate
```

I don't think I fully understand the use case surrounding `validate` yet so that didn't help. When I read the doc for `validate` I am not sure the text flows correctly:

```
The errors will not immediately halt parsing on this path, but instead it will continue, potentially emitting one or more other errors, only failing after the pattern has otherwise successfully, or emitted another terminal error.
```

I don't understand "after the pattern has otherwise successfully" - is the grammar correct?

**Comment by zesterer** [comment]
I think the docs here need a little work. That said, I can explain things here:

Parsers can generate both 'primary' and 'secondary' errors. Primary errors are fatal to the parser and result in no output being generated. For example, `just('a')` will generate a primary error if it sees anything other than `'a'` as the next token in the input.

Secondary errors are more unique to chumsky. Sometimes parsers encounter syntax errors that are recoverable. For example, it might be possible for the parser to skip to the next semicolon (or any number of other [strategies](https://docs.rs/chumsky/1.0.0-alpha.4/chumsky/recovery/index.html)) and emit an error AST node instead of failing outright. In this case, parsing can continue, producing an output value.

If a `try_map` closure produces an `Err(...)`, a primary error is produced and the parser backtracks.

If a `validate` closure emits errors, only secondary errors are emitted: the parser does not backtrack and continues as it was. This is useful in cases where you want to liberally accept more input than is strictly valid (such as having a `u8` literal parser that accepts any integer, but should produce an error if the literal is out of range of a `u8`).
