### ISSUE TITLE
Example foo.rs fails to parse expr in parentheses

### ISSUE THREAD

**Issue by KSchala** [zesterer/chumsky#491]
I was playing with the example foo.rs but it fails with the following code
```
let x = (123);
x + 123
```
-> Parse error: found "x" but expected one of "/", "+", "-", end of input, "*"

Can somebody give me a hint why this does not work? Cause otherwise parenthesed exprs just work..

**Comment by Zij-IT** [comment]
So this one is actually pretty funny. This fails because of the grouping `(123)`, but the reason isn't actually related strictly to the grouping.

If you modify the parser of the example to use `extra::Err<Rich<'a, char>>` you will see that the parser errors at the first `x`, and not the second, despite the rather odd error message.

Since we know it fails when introducing the grouping, I decided to take a look at how grouped expression parsing differs from number parsing. And infact there is one key difference:

```rust
        let int = text::int(10)
            .map(|s: &str| Expr::Num(s.parse().unwrap()))
            .padded();

        let atom = int
            // Grouping happens here
            .or(expr.delimited_by(just('('), just(')')))
            .or(call)
            .or(ident.map(Expr::Var));
```

The subtle but all important difference is that a grouping is the *only* parser that isn't padded at the start. You can verify that this is why it fails by removing the leading whitespace in front of the opening parenthesis in your test input.

**Comment by KSchala** [comment]
Ah yes, thank you very much :)

**Comment by Zij-IT** [comment]
Not a problem! I appreciate you writing an issue to bring it to our attention :) As a sidenote: I think this is another great example of why it is best to separate the lexing and parsing step into two steps, instead of doing what foo does, and doing it all in one.

**Comment by Zij-IT** [comment]
I take it I can close the pull request then :D

**Comment by KSchala** [comment]
Thanks to both of you!
