### ISSUE TITLE
Support parsing nested inputs

### ISSUE THREAD

**Issue by CraftSpider** [zesterer/chumsky#50]
Currently, there's no clean way to do something like
```rs
parse_keyword()
    .then_with(|kw| parser(kw))
```
Creating a parser that requires the ok result of the previous parser. It's possible with `custom`, but definitely kind of ugly.

**Comment by zesterer** [comment]
This is, unfortunately, more complicated than it may seem on the surface.

Although superficially it may seem like a case of mapping the output, there's a lot of error routing going on behind the scenes by Chumsky that is deliberately left hidden because it's quite confusing to work with directly. This error routing uses the location (in the original input stream) that an error was encountered at to make decisions about when it should prioritise it over other errors. In this case, we effectively have two nested streams (the original input, and the new keyword stream) that have completely incompatible notions of 'location' and so doing sensible error routing is impossible.

There is the `try_map` combinator that allows this to work today, but it is rather limited: the two parsers can't really communicate with one-another, all the inner parser can do is fail entirely or not fail at all.

This feature is useful for more things though: nested inputs are quite common (Rust, for example, uses a lexer that generates [token trees](https://doc.rust-lang.org/proc_macro/enum.TokenTree.html)). Chumsky currently has the `Stream::from_nested` function that provides a somewhat hacky way to alleviate this for most purposes, but it's far from perfect and having a parser that can truly parse recursive inputs would be rather useful.

I have a few ideas about resolving this that I'm slowly developing so I'll keep this issue open, but it's unlikely that Chumsky will grow this feature very soon.

**Comment by zesterer** [comment]
I'm going to change the title of this issue to more accurately reflect the problem.

**Comment by CraftSpider** [comment]
I was actually thinking of a slightly different case, where the returned value is used to *create* a parser, but that new parser still operates on the original `Stream`. I'm looking for basically a way to write this pattern:
```rs
just("a").then(...)
    .or(just("b").then(...))
    ...
    .or(just("\u{XXXX}").then(...))
```
for a number of cases impractical to spell out by hand.

**Comment by zesterer** [comment]
Ah, fair enough. I think, in practice, solving nested parsing will *probably* just yield a solution to this too, but I'll bear in mind that they're not quite the same.

**Comment by CraftSpider** [comment]
Update: In relation to my original problem in the nested input issue, I wrote up a `custom()` that does roughly what I want, except that I can't actually use it because the `Stream` and `Silent::new` methods are all private. I think it doesn't have the relevant error issue, as it only uses the original stream. Thoughts on this (Is this already possible some other way? did I mess up any of the PResult handling?) / would this be acceptable to add, as it appears impossible to do from an external crate? Given, if it was added, it would likely be as an actual `Parser` type instead of a `custom`.

(Also, thanks for your patience with all my issues/requests.)

<details>
     <summary>Custom Impl</summary>

```rs
pub fn then_with<I: Clone, O1: Clone, O2, P2: Parser<I, O2, Error = E>, E: Error<I>, F: Fn(O1) -> P2>(
    first: impl Parser<I, O1, Error = E>,
    make_second: F
) -> impl Parser<I, O2, Error = E>
{
    custom(move |stream: &mut StreamOf<I, E>| -> PResult<I, O2, E> {
        let state = stream.save();

        let first_result = first.parse_inner(&mut Silent::new(), stream);

        match first_result {
            (mut first_errs, Ok((first_output, first_alt))) => {
                let second = make_second(first_output);
                let second_result = second.parse_inner(&mut Silent::new(), stream);
                match second_result {
                    (second_errs, Ok((second_output, second_alt))) => {
                        first_errs.extend(second_errs);
                        (first_errs, Ok((second_output, first_alt.or(second_alt))))
                    }
                    (second_errs, Err(e)) => {
                        stream.revert(state);
                        first_errs.extend(second_errs);
                        (first_errs, Err(e))
                    }
                }
            },
            (errs, Err(e)) => {
                stream.revert(state);
                (errs, Err(e))
            }
        }
    })
}
```
</details>

**Comment by zesterer** [comment]
> Thoughts on this

While your implementation is correct, I'm quite hesitant to reveal these API features because they're not really intended for consumption by users and are mostly undocumented/subject to change.

**Comment by zesterer** [comment]
It could, although prioritisation of error messages would be a little weird. It's likely that the resulting errors might not point to the true underlying error. I'm happy to accept a PR with a combinator like this though.

**Comment by zesterer** [comment]
Going to close this because #269 pretty much covers this use-case (at least, to the extent that we're happy with).
