### ISSUE TITLE
What would be the right way to parse punctuation like ">>"?

### ISSUE THREAD

**Issue by lachlansneff** [zesterer/chumsky#55]
I'm trying to parse a language with a bunch of type of punctuation, many of them similar to rust. It doesn't seem difficult to parse single-char punctuation, but I'm not sure what parser combinators to plug together to be able to parse text into the tokens with multiple characters:

```rust
pub enum Punctuation {
    Plus, // +
    Minus, // -
    Star, // *
    Slash, // /
    Percent, // %
    Caret, // ^
    Not, // !
    And, // &
    Or, // |
    AndAnd, // &&
    OrOr, // ||
    Shl, // <<
    Shr, // >>
    Eq, // =
    EqEq, // ==
    Ne, // !=
    Gt, // >
    Lt, // <
    Ge, // >=
    Le, // <=
    Underscore, // _
    Dot, // .
    Comma, // ,
    Semi, // ;
    Colon, // :
    PathSep, // ::
    RArrow, // ->
    FatArrow, // =>
}
```

**Comment by zesterer** [comment]
If you're using the `master` branch, `just("&&")` will parse the sequence `&&`. If you're using the latest stable release, `seq("&&".chars())` will do the same thing.

Make sure to put "less general" patterns first (i.e: parsing `->` should be attempted before `-` in order to avoid it being accidentally parsed as distinct `-` and `>` tokens).

A good example of parsing such patterns can be found in [the lexer for my own language](https://github.com/zesterer/tao/blob/master/syntax/src/token.rs#L152-L179). You might also find the `nano_rust` example in the repository useful.

**Comment by lachlansneff** [comment]
Thank you! The lexer that you wrote for tao was very useful!

**Comment by zesterer** [comment]
Something that might interest you: yesterday, I added a `choice` combinator that should compile faster and have better performance than an `or` chain. It's already in the `master` branch and will be available in the next stable release. Here's an example of it in action:

```rs
#[derive(Clone, Debug, PartialEq)]
enum Token {
    If,
    For,
    While,
    Fn,
    Int(u64),
    Ident(String),
}

let tokens = choice::<_, Simple<char>>((
    text::keyword("if").to(Token::If),
    text::keyword("for").to(Token::For),
    text::keyword("while").to(Token::While),
    text::keyword("fn").to(Token::Fn),
    text::int(10).from_str().unwrapped().map(Token::Int),
    text::ident().map(Token::Ident),
))
    .padded()
    .repeated();

use Token::*;
assert_eq!(
    tokens.parse("if 56 for foo while 42 fn bar"),
    Ok(vec![If, Int(56), For, Ident("foo".to_string()), While, Int(42), Fn, Ident("bar".to_string())]),
);
```

**Comment by lachlansneff** [comment]
Ah fantastic, `choice` works very well!
