### ISSUE TITLE
stack overflow

### ISSUE THREAD

**Issue by viperML** [zesterer/chumsky#554]
I am having a stack overflow and I don't know how to start hunting it.

The source code for the parser is located here: https://github.com/viperML/len/blob/fd93282fdb50d181af7652526b3b308475fefac1/src/ast.rs#L43

(The overflow can be triggered with `cargo test` or with the language repl with `cargo run` and typing anything, like a literal `1` )

This has started ocurring after adding a `.delimited_by` to repeatedly parse my lang's struct elements (`foo: val , bar: val`) (I haven't added yet the delimited by {}) https://github.com/viperML/len/blob/fd93282fdb50d181af7652526b3b308475fefac1/src/ast.rs#L71

The error might have some interaction with the pratt parsers at the end of the function, as returning early the atom won't trigger a SO.

**Comment by zesterer** [comment]
The most likely candidate here is the use of `atom` inside the pratt parser at the bottom.

```rs
atom.clone().pratt((
    prefix(3, atom, |op: Ast, o: Ast| {
        Ast::FunctionCall(FunctionCall {
            function: Box::new(op),
            argument: Box::new(o),
        })
    }),
    ...
))
```

This looks for an `atom` directly before another `atom`, which I think it likely to result in infinite recursion. What happens if you comment out this operator?

Regardless, I think function calls are better expressed as `postfix` operators, with the args trailing afterward.

**Comment by viperML** [comment]
Ineed, it seems that `prefix` operator is the cause.

Just changing it to a `postfix` however, it seems that it enters an infinite loop. The parser doesn't crash immediately, but seems to loop without stop.

**Comment by zesterer** [comment]
Infinite loop is better (and makes sense given how pratt parsers work)!

So I think the problem here is that the rule contains itself. Every time it tries to recurse into `atom`, it sees `atom` right there as a candidate pattern. It's effectively just a strange form of left recursion.

My advice would be to parse function application specifically using operator precedence (i.e: have a distinct rule like the following):

```rs
let atom = ... ;

let app = atom.foldl(app.repeated(), ...);

app.pratt((
    // All of the other ops here
))
```

Ofc you can switch the order if you want to reduce the precedence of function application too.

**Comment by viperML** [comment]
You are right, moving the function application to that different parser fixes the issue. Initially that was my implementation (for the infix operators too), but I moved too much into the pratt.

On a unrelated note, thank you and the contributors for this amazing lib :+1:
