### ISSUE TITLE
Pratt parsing with non-associative operators

### ISSUE THREAD

**Issue by rmehri01** [zesterer/chumsky#557]
Hey there, thanks for this crate, it's really nice to work with :)

I was wondering if it's possible to parse non-associative operators with the pratt parsing feature, for example to turn `x == y == z` into `x == y && y == z` or have a parse error instead?

**Comment by zesterer** [comment]
I think the easiest approach to this is to perform this transformation after parsing. `x == y == z` is ambiguous during parsing: it could be intepreted as `(i32 == i32) == bool` (and indeed I think most languages will interpret it as such, with Rust being a notable exception since it special-cases this). Disambiguating these cases is probably best done by a pass that has more information about the code than the parser itself.

**Comment by rmehri01** [comment]
Ah okay, that makes sense, thanks!
