### ISSUE TITLE
Input lifetimes

### ISSUE THREAD

**Issue by nodir-t** [zesterer/chumsky#585]
Hi! Brilliant library! Love it.

I've recently switched from 0.9 to 1.0 and the developer experience got worse, specifically related to having to deal with input lifetimes.

It was very nice to have a bunch of functions that each returns a parser, e.g.

```
fn string() -> impl Parser<Expression> { ... }
fn boolean() -> impl Parser<Expression> { ... }

trait Parser<O>: RawParser<char, O, Error = Error> + Sized + Clone + 'static {...}

type Error = Simple<'static, char>;
```

after switching to 10, now I have to accept <'a> in each function, although *the function does not actually care* - I think there is a design improvement opportunity here. Currently combinators return parsers, which accept concrete input. Can they conceptually return a *function* that returns a parser? That way the user of a combinator wouldn't have to deal with things they don't care about.

**Comment by nodir-t** [comment]
I can live with it though. Now the code looks like this:

```
fn string<'i>() -> impl Parser<'i, Expression> { ... }
fn boolean<'i>() -> impl Parser<'i, Expression> { ... }
```

which isn't too bad

**Comment by Zij-IT** [comment]
The example you’ve posted is definitely how the lifetimes are intended to be used. I can totally understand how switching from .9 to 1.0 was rough though.

There is work being done on a migration guide if I am not mistaken, that should hopefully limit these pains in the future (:

**Comment by nodir-t** [comment]
I guide would definitely help. I think I already figured out most of it (I was missing `chain`, for example), but it took me a day. A guide would reduce that time spend

**Comment by zesterer** [comment]
Unfortunately, this is mostly due to limitations in Rust's lifetime solver. Ideally, we'd have retained `Parser` not having a lifetime and instead do something like this:

```rs
trait Parser {
    type Input<'a>;
    type Output<'a>;

    fn parse<'a>(&self, input: Self::Input<'a>) -> ParseResult<Self::Output<'a>>;
}

// And therefore parser functions could look like
fn expr_parser() -> impl for<'src> Parser<Input<'src> = &'src str, Output<'src> = Expr<'src>> { ... }
```

Unfortunately, due to horribleness around variance rules, Rust doesn't currently accept this (and is unlikely to any time in the near future), so we're stuck with binding parsers to the lifetime of the input that they parse. In `1.0.0-alpha.6` we introduced [`Cache`](https://docs.rs/chumsky/1.0.0-alpha.6/chumsky/cache/index.html), which allows safely writing parsers independently of a specific lifetime thanks to a GAT trick, although it's admittedly a little more awkward than I'd prefer.

Regarding `chain`: this functionality is mostly replaced by the ability to take slices of the input (see the `to_slice` combinator).
