### ISSUE TITLE
In big sequences of just's separated by or's, is it preferred to map the ouput every time or match at the end?

### ISSUE THREAD

**Issue by AverageLinuxEnjoyer** [zesterer/chumsky#635]
I couldn't come up with a better way to ask the question, but it should be clear from the following example:
```rust
    let ctrl = just(';').to(Token::Ctrl(Ctrl::Semicolon))
        .or(just(',').to(Token::Ctrl(Ctrl::Comma)))
        .or(just('(').to(Token::Ctrl(Ctrl::LParen)))
        .or(just(')').to(Token::Ctrl(Ctrl::RParen)))
        .or(just('[').to(Token::Ctrl(Ctrl::LSquare)))
        .or(just(']').to(Token::Ctrl(Ctrl::RSquare)))
        .or(just('{').to(Token::Ctrl(Ctrl::LCurly)))
        .or(just('}').to(Token::Ctrl(Ctrl::RCurly)))
        .padded();
```
vs
```rust
let ctrl = just(';')
    .or(just(','))
    .or(just('('))
    .or(just(')'))
    .or(just('['))
    .or(just(']'))
    .or(just('{'))
    .or(just('}'))
    .padded()
    .map(|t| match t {
        ";" => Token::Ctrl(Ctrl::Semicolon),
        "," => Token::Ctrl(Ctrl::Comma),
        "(" => Token::Ctrl(Ctrl::LParen),
        ")" => Token::Ctrl(Ctrl::RParen),
        "[" => Token::Ctrl(Ctrl::LSquare),
        "]" => Token::Ctrl(Ctrl::RSquare),
        "{" => Token::Ctrl(Ctrl::LCurly),
        "}" => Token::Ctrl(Ctrl::RCurly),
        _ => unreachable!(),
    });

```
I would assume the first one should create a longer type, therefore longer compile times. Is that the case? Which one would be faster at runtime?

**Comment by CraftSpider** [comment]
The first one is normally preferred. In this case the type effects of Or will be minimal, as it forms a list not a tree, though if you really care, `choice` is equivalent to chained `or`s. In terms of runtime performance, I imagine the first will be faster, since it will form a single lookup of char to tokens, instead of creating a char check, then converting the char to a token possibly after losing the range info, so it may include the panic branch despite it being unreachable.

**Comment by AverageLinuxEnjoyer** [comment]
Great answer, thanks a lot!
